alias c="clear"
alias cat="bat --paging=never"
alias ..="cd .."
alias ...="cd ../.."
alias l="eza -lbF --git"
alias ls="eza --icons=always --color=always --group-directories-first"
alias lt="eza --tree --level=2 --icons"
alias vi="nvim"
alias hc="history -p"
alias gs="git status"
alias gp="git push"
alias gco="git checkout"
alias gfb="git branch --all | grep "

eval "$(devbox global shellenv)"
eval "$(sheldon source)"
