tap "simoarpe/ziggity"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Modern, maintained replacement for ls
brew "eza"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# Distributed revision control system
brew "git"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Pretty, minimal and fast ZSH prompt
brew "pure"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Internet file retriever
brew "wget"
# Terminal UI for Git, written in Zig
brew "simoarpe/ziggity/ziggity", trusted: true
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
npm "corepack"
